env:
  node: true
  jest/globals: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
rules:
  indent:
    - error
    - 2
    - MemberExpression: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  jest/no-disabled-tests:
    - warn
  jest/no-focused-tests:
    - error
  jest/no-identical-title:
    - error
  jest/valid-expect:
    - error
plugins:
  - jest